name: local_cards
description: "Save your cards securely & locally on your device"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: 3.27.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
